###
# This file configures the project "Piper" pipeline of your project.
# For a reference of the configuration concept and available options, please have a look into its documentation.
#
# The documentation for the most recent pipeline version can always be found at:
#    https://sap.github.io/jenkins-library/
#
# This is a YAML-file. YAML is an indentation-sensitive file format. Please make sure to properly indent changes to it.
###



# ### General project setup
# general:
#   inferBuildTool: true

# ### Step-specific configuration
# steps:
#   mavenExecute:
#     dockerImage: devxci/mbtci:1.0.14

#   artifactPrepareVersion:
#     versioningType: cloud_noTag

# ### Stage-specific configuration
# stages:
#   'Confirm':
#     manualConfirmation: false

# #  Integration:
# #    credentials:
# #      - alias: 'mySystemAlias'
# #        credentialId: 'mySystemCredentialsId'

# #  Release:
# #    cfTargets:
# #      - org: 'myOrg'
# #        space: 'mySpace'
# #        apiEndpoint: 'https://'
# #        appName: 'myAppName'
# #        manifest: 'manifest.yml'
# #        credentialsId: 'myDeploymentCredentialsId'


general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      apiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
      org: '76135463trial'
      space: 'dev'
      credentialsId: 'mdpert'
    # TMS에 대해서 적용시 필요
    # tmsUpload:
    #   credentialsId: 'tmscicd'
    #   nodeName: 'pre-PRD'
    #   mtaPath: 'FioriDemo'
    #   customDescription: 'CAP CDS on JAVS Test Project'
